services:
  - type: web
    name: tinta-tonic
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: errorlog
      - key: APP_URL
        value: https://tinta-tonic.onrender.com
      - key: APP_KEY
        generateValue: true
